In [ ]:
import torch

In [ ]:
x = torch.ones(2,2,requires_grad=True) #변수 선언
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
 y = x+1 #모델 내 연산 예측값 산출
 print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [ ]:
z = 2*y**2 #손실함수 계산
res = z.mean()

In [ ]:
print(res) #손실 산출

tensor(8., grad_fn=<MeanBackward0>)


In [ ]:
#d(res)/dx_i = x_i + 1
#res = (z_1 + .. + z_4)/4
#z_i = 2y_i**2
#z_i = 2(x_i+1)**2
res.backward()

In [ ]:
print(x.grad) #x 미분값

tensor([[2., 2.],
        [2., 2.]])


In [ ]:
#실제로는 이러한 라이브러리 사용
import torch.nn as nn
import torch.nn.functional as F