In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.empty(5,4) #빈 텐서 생성
print(x)

tensor([[1.1932e+37, 3.0684e-41, 7.0065e-44, 6.8664e-44],
        [6.3058e-44, 6.7262e-44, 7.2868e-44, 6.3058e-44],
        [6.8664e-44, 7.9874e-44, 1.1771e-43, 6.7262e-44],
        [7.7071e-44, 8.1275e-44, 7.0065e-44, 7.7071e-44],
        [8.1275e-44, 7.4269e-44, 7.7071e-44, 6.4460e-44]])


In [ ]:
torch.ones(3,3) #1행렬 생성

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2) #0행렬 생성

tensor([0., 0.])

In [ ]:
torch.rand(5,6) #랜덤행렬 생성

tensor([[0.4188, 0.4818, 0.9234, 0.0385, 0.0462, 0.1360],
        [0.0476, 0.3940, 0.3005, 0.7228, 0.3438, 0.3048],
        [0.8060, 0.2324, 0.5521, 0.3503, 0.4682, 0.0250],
        [0.7744, 0.4743, 0.2038, 0.8758, 0.8891, 0.1278],
        [0.6402, 0.6092, 0.0664, 0.4569, 0.6122, 0.3461]])

In [ ]:
l=[13,4]
r = np.array([4,56,7])

In [ ]:
torch.tensor(l)

tensor([13,  4])

In [ ]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [ ]:
x.size()

torch.Size([5, 4])

In [ ]:
type(x)

torch.Tensor

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.8276, 0.6600],
        [0.0244, 0.0973]])
tensor([[0.8367, 0.8099],
        [0.2688, 0.6978]])


In [ ]:
x+y

tensor([[1.6643, 1.4699],
        [0.2932, 0.7950]])

In [ ]:
torch.add(x,y)

tensor([[1.6643, 1.4699],
        [0.2932, 0.7950]])

In [ ]:
y.add(x) #단순 연산

tensor([[1.6643, 1.4699],
        [0.2932, 0.7950]])

In [ ]:
y.add_(x) #y에 x를 더해서 y를 대체

tensor([[1.6643, 1.4699],
        [0.2932, 0.7950]])

In [ ]:
y[1,1]

tensor(0.7950)

In [ ]:
x = torch.rand(8,8)
print(x)

tensor([[0.7985, 0.9586, 0.0936, 0.6015, 0.0099, 0.4372, 0.2192, 0.4064],
        [0.4147, 0.2459, 0.5293, 0.9217, 0.9128, 0.7772, 0.1042, 0.0687],
        [0.2678, 0.2675, 0.0941, 0.4597, 0.5267, 0.2335, 0.2287, 0.7420],
        [0.0362, 0.2976, 0.6389, 0.6851, 0.4085, 0.2209, 0.0300, 0.1444],
        [0.7941, 0.4518, 0.1388, 0.8507, 0.3444, 0.3862, 0.3697, 0.3293],
        [0.4274, 0.0458, 0.7738, 0.0147, 0.3515, 0.5868, 0.7487, 0.9688],
        [0.7598, 0.2477, 0.3148, 0.4699, 0.0075, 0.9349, 0.7015, 0.2421],
        [0.8175, 0.8556, 0.5231, 0.0368, 0.6617, 0.7953, 0.6047, 0.5940]])


In [ ]:
x.view(64) #한 열로 표현

tensor([0.7985, 0.9586, 0.0936, 0.6015, 0.0099, 0.4372, 0.2192, 0.4064, 0.4147,
        0.2459, 0.5293, 0.9217, 0.9128, 0.7772, 0.1042, 0.0687, 0.2678, 0.2675,
        0.0941, 0.4597, 0.5267, 0.2335, 0.2287, 0.7420, 0.0362, 0.2976, 0.6389,
        0.6851, 0.4085, 0.2209, 0.0300, 0.1444, 0.7941, 0.4518, 0.1388, 0.8507,
        0.3444, 0.3862, 0.3697, 0.3293, 0.4274, 0.0458, 0.7738, 0.0147, 0.3515,
        0.5868, 0.7487, 0.9688, 0.7598, 0.2477, 0.3148, 0.4699, 0.0075, 0.9349,
        0.7015, 0.2421, 0.8175, 0.8556, 0.5231, 0.0368, 0.6617, 0.7953, 0.6047,
        0.5940])

In [ ]:
x.view(-1,16) #나머지 값이 고정되어야 자동값 대입, -1은 하나만 표현

tensor([[0.7985, 0.9586, 0.0936, 0.6015, 0.0099, 0.4372, 0.2192, 0.4064, 0.4147,
         0.2459, 0.5293, 0.9217, 0.9128, 0.7772, 0.1042, 0.0687],
        [0.2678, 0.2675, 0.0941, 0.4597, 0.5267, 0.2335, 0.2287, 0.7420, 0.0362,
         0.2976, 0.6389, 0.6851, 0.4085, 0.2209, 0.0300, 0.1444],
        [0.7941, 0.4518, 0.1388, 0.8507, 0.3444, 0.3862, 0.3697, 0.3293, 0.4274,
         0.0458, 0.7738, 0.0147, 0.3515, 0.5868, 0.7487, 0.9688],
        [0.7598, 0.2477, 0.3148, 0.4699, 0.0075, 0.9349, 0.7015, 0.2421, 0.8175,
         0.8556, 0.5231, 0.0368, 0.6617, 0.7953, 0.6047, 0.5940]])

In [ ]:
x.view(-1,4,4)

tensor([[[0.7985, 0.9586, 0.0936, 0.6015],
         [0.0099, 0.4372, 0.2192, 0.4064],
         [0.4147, 0.2459, 0.5293, 0.9217],
         [0.9128, 0.7772, 0.1042, 0.0687]],

        [[0.2678, 0.2675, 0.0941, 0.4597],
         [0.5267, 0.2335, 0.2287, 0.7420],
         [0.0362, 0.2976, 0.6389, 0.6851],
         [0.4085, 0.2209, 0.0300, 0.1444]],

        [[0.7941, 0.4518, 0.1388, 0.8507],
         [0.3444, 0.3862, 0.3697, 0.3293],
         [0.4274, 0.0458, 0.7738, 0.0147],
         [0.3515, 0.5868, 0.7487, 0.9688]],

        [[0.7598, 0.2477, 0.3148, 0.4699],
         [0.0075, 0.9349, 0.7015, 0.2421],
         [0.8175, 0.8556, 0.5231, 0.0368],
         [0.6617, 0.7953, 0.6047, 0.5940]]])

In [ ]:
y = x.numpy()
print(y)

[[0.7985042  0.9585818  0.09360725 0.6014551  0.00990963 0.4371863
  0.21916813 0.40641677]
 [0.4147228  0.24588567 0.52931076 0.9216913  0.9128284  0.7771659
  0.10418057 0.06866252]
 [0.26782328 0.26746422 0.0941084  0.4597184  0.52671236 0.23346627
  0.22865582 0.7419593 ]
 [0.03621548 0.29755628 0.63892865 0.68511844 0.4085058  0.2209301
  0.02996534 0.14435732]
 [0.79411465 0.4518438  0.13876188 0.85071784 0.34435457 0.38619137
  0.36967164 0.3292812 ]
 [0.42744386 0.04578793 0.7738349  0.01466942 0.3514809  0.5867978
  0.74866545 0.9688008 ]
 [0.7598258  0.24769789 0.31484216 0.46987587 0.00748169 0.93494457
  0.7015078  0.24212438]
 [0.81749517 0.85559833 0.52308875 0.03678441 0.6617474  0.7952991
  0.60467476 0.59396994]]


In [ ]:
type(y)

numpy.ndarray

In [ ]:
x = torch.ones(1)

In [ ]:
x #텐서

tensor([1.])

In [ ]:
x.item() #x안의 값을 뽑아낼 때, 사용/ loss값 뽑아낼 때 사용

1.0